name: CI/CD

on:
    push:
        branches: [dev]

jobs:
    build-and-deploy:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v4

            - name: Build and push Docker images
              env:
                  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
                  DOCKER_HUB_ACCESS_TOKEN:
                      ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
              run: |
                  echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
                  docker build -t $DOCKER_HUB_USERNAME/simple-cms-frontend:dev .
                  docker push $DOCKER_HUB_USERNAME/simple-cms-frontend:dev

            - name: Copy docker-compose.yml and Dockerfile to server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USERNAME }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  source: docker-compose.yml, Dockerfile
                  target: ~/app/simple-cms-frontend

            - name: Copy nginx.conf to server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USERNAME }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  source: 'nginx.conf'
                  target: ~/app/simple-cms-frontend

            - name: Deploy to server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USERNAME }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  script: |
                      cd ~/app/simple-cms-frontend
                      docker-compose pull
                      docker-compose down
                      docker-compose up -d
                      docker cp nginx.conf simple-cms-frontend-1:/etc/nginx/nginx.conf
